### ISSUE TITLE
How to test my own data

### ISSUE THREAD

**Issue by JaneCX** [JingchunCheng/FAVOS#2]
I found that if I wanna use my own data, I have to use the .mat.mat file in the part-tracking folder. So how could I generate this file? Do I need to use the tracker first?

**Comment by wasidennis** [comment]
Hi @JaneCX, we are working on a version integrating the part tracker. If you want to run on your sequences, currently you would need to first run SiaFC (https://github.com/bertinetto/siamese-fc) to get those part tracking results.

**Comment by YuanLeung** [comment]
@wasidennis 
For the 50 images in Blackswan, why your tracking result in 'blackswan.mat.mat'  have 246 boxes for each image?

**Comment by YuanLeung** [comment]
Hi @wasidennis, since you have 50 images in Blackswan and each with one swan, why your tracking result in 'blackswan.mat.mat' have 246 boxes for each image. How you produce them?

**Comment by YuanLeung** [comment]
Hi @wasidennis , how could I get baseline mask of my own data ?
