### ISSUE TITLE
How to test your own tracking results?

### ISSUE THREAD

**Issue by vincennnnt** [JingchunCheng/FAVOS#3]
Sorry to interrupt u.I just have got my tracking results,the images with bounding boxes ,but how can i test ur ROI SegNet with my tracking results?I hope u could give me some advice.Thank u so much!!!

**Comment by JingchunCheng** [comment]
Hi, @vincennnnt 

You can refer to the code in "demo/infer_davis16.py", where _input_roi_ (line 128-133) stores the input boxes (the size of this variable is N*5, each row denotes one box: 0 xmin ymin xmax ymax).

You can modify the code to load your own tracking results and assign them to _input_roi_ for each image to test with ROISegNet.

**Comment by vincennnnt** [comment]
Cool！Thank u for ur reply and ur great work
